version: '3'
services:
  studygolang:
    container_name: studygolang
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8088:8088
    depends_on:
      - db
      - redis
    volumes:
      - ./static:/app/studygolang/static
      - ./template:/app/studygolang/template
      - ./log:/app/studygolang/log

  db:
    image: "mysql:5.7.26"
    container_name: go-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: studygolang
      MYSQL_USER: studygolang
      MYSQL_PASSWORD: studygolangpassword

  redis:
    image: "redis:alpine"
    container_name: go-redis
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
